# config/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ruby_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:3000'] # 'web' - це назва контейнера з твоїм сайтом